version: "3"

services:   
  app: 
    build: .
    command: npm start
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    environment:
      - dbhost=mongodb

  mongodb:
    image: "bitnami/mongodb:latest"
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net
    
networks:
  net:
    driver: bridge
