version: "3"

services:   
  app: 
    build: .
    restart: always
    tty: true
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: "bitnami/mongodb:latest"
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
