version: "3"

services: 
  app: 
    build: .
    command: npm start
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"